{% set version = "0.2.17" %}

package:
  name: fmpy
  version: {{ version }}

source:
  url: https://github.com/CATIA-Systems/FMPy/archive/v{{ version }}.tar.gz
  sha256: a1460271190cfe9b32779b2cc78591ad09ca15475c8a13761cb10d33840d48c1
  # macOS: shasum -a 256 <file>

build:
  number: 1
  skip: True  # [win and vc<14]
  entry_points:
    - fmpy = fmpy.command_line:main

outputs:
  - name: fmpy-base
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"
    requirements:
      build:
        - python
        - pip
        - lxml
        - numpy
        - pathlib
        - pyqt
        - pywin32  # [win]
      run:
        - python
        - lxml
        - numpy
        - pathlib
        - pywin32  # [win]
    test:
      imports:
        - fmpy
        - fmpy.ssp
        - fmpy.ssp.examples
        - fmpy.sundials

  - name: fmpy
    requirements:
      run:
        - dask
        - fmpy-base
        - matplotlib
        - pyqt
        - pyqtgraph
        - requests
    test:
      imports:
        - fmpy
        - fmpy.cross_check
        - fmpy.examples
        - fmpy.gui
        - fmpy.ssp
        - fmpy.ssp.examples
        - fmpy.sundials

about:
  home: https://github.com/CATIA-Systems/FMPy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Simulate Functional Mockup Units (FMUs) in Python'
  doc_url: https://fmpy.readthedocs.io/
  dev_url: https://github.com/CATIA-Systems/FMPy

extra:
  recipe-maintainers:
    - t-sommer
    - wulmer
