{% set version = "0.2.21" %}

package:
  name: fmpy
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/5e/89/fa556c4f9ac56d466e229dceaa5cbc3993308c5c9574f739964f853415bb/FMPy-0.2.21-py2.py3-none-any.whl
  sha256: cb83e27e072f0078f82080aae32b3307d16a30806a1f05d47a755204c1127415
  # macOS: shasum -a 256 <file>

build:
  number: 0
  skip: true  # [win and vc<14]
  script: {{ PYTHON }} -m pip install --no-deps -vv *.whl

  entry_points:
    - fmpy = fmpy.command_line:main

requirements:
  build:
    - python
    - pip
    - lxml
    - numpy
    - pathlib
    - pyqt
    - pywin32  # [win]
  run:
    - python
    - dask
    - lxml
    - matplotlib-base
    - numpy
    - pathlib
    - pyqt
    - pyqtgraph
    - pywin32  # [win]
    - requests

test:
  imports:
    - fmpy
    - fmpy.cross_check
    - fmpy.examples
    - fmpy.gui
    - fmpy.ssp
    - fmpy.ssp.examples
    - fmpy.sundials

about:
  home: https://github.com/CATIA-Systems/FMPy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Simulate Functional Mockup Units (FMUs) in Python
  doc_url: https://fmpy.readthedocs.io/
  dev_url: https://github.com/CATIA-Systems/FMPy

extra:
  recipe-maintainers:
    - t-sommer
    - wulmer
