package:
  name: fmpy
  version: 0.3.21

source:
  url: https://files.pythonhosted.org/packages/22/ee/974c39c5476ce20342a38483060450bd75f3cd5bb7b2c7ba712d63e763e3/FMPy-0.3.21-py3-none-any.whl
  sha256: 77d6896cbd4737ad8e11a185bd3eb54f1c71d3e22c6308b4e8ed55e39142fe80
  # macOS: shasum -a 256 <file>
  # Windows: certutil -hashfile <file> SHA256

build:
  number: 0
  skip: true  # [win and vc<14]
  entry_points:
    - fmpy = fmpy.command_line:main

outputs:

  - name: fmpy-base
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    requirements:
      host:
        - python >=3.5
        - pip
      run:
        - python >=3.5
        - attrs
        - jinja2
        - lark
        - lxml
        - msgpack-python
        - numpy
        - pywin32  # [win]
    test:
      imports:
        - fmpy
        - fmpy.cross_check
        - fmpy.examples
        - fmpy.fmucontainer
        - fmpy.modelica
        - fmpy.ssp
        - fmpy.sundials  # [not linux]

  - name: fmpy
    build:
      noarch: python
    requirements:
      run:
        - dash-bootstrap-components >=1.0.0
        - dask
        - matplotlib-base
        - notebook
        - plotly
        - pyqt
        - pyqtgraph
        - pyqtwebengine
        - python-kaleido
        - requests
        - scipy
        - {{ pin_subpackage('fmpy-base', max_pin="x.x.x") }}
    test:
      imports:
        - fmpy.gui
        - fmpy.webapp

about:
  home: https://github.com/CATIA-Systems/FMPy
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Simulate Functional Mockup Units (FMUs) in Python
  doc_url: https://fmpy.readthedocs.io/
  dev_url: https://github.com/CATIA-Systems/FMPy

extra:
  recipe-maintainers:
    - t-sommer
    - wulmer
