package:
  name: fmpy
  version: 0.3.12

source:
  url: https://files.pythonhosted.org/packages/ca/dd/56785d53f50de8b99a442e17271fea25519ecc42b4fd9008acca64b0e93c/FMPy-0.3.12-py3-none-any.whl
  sha256: 00d952f86f8c2399836ad48aa7512ab13248280c3bafbfed3d93bfa63bc5b5a0
  # macOS: shasum -a 256 <file>
  # Windows: certutil -hashfile <file> SHA256

build:
  number: 1
  skip: true  # [win and vc<14]
  entry_points:
    - fmpy = fmpy.command_line:main

outputs:

  - name: fmpy-base
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - attrs
        - jinja2
        - lark-parser
        - lxml
        - msgpack-python
        - numpy
        - pathlib
        - pywin32  # [win]
        - pytz
        - requests
    test:
      imports:
        - fmpy
        - fmpy.cross_check
        - fmpy.examples
        - fmpy.fmucontainer
        - fmpy.modelica
        - fmpy.ssp
        - fmpy.sundials

  - name: fmpy
    build:
      noarch: python
    requirements:
      run:
        - dash-bootstrap-components
        - dask
        - matplotlib-base
        - nbformat
        - pyqt
        - pyqtgraph
        - {{ pin_subpackage('fmpy-base', max_pin="x.x.x") }}
    test:
      imports:
        - fmpy.gui
        - fmpy.webapp

about:
  home: https://github.com/CATIA-Systems/FMPy
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Simulate Functional Mockup Units (FMUs) in Python
  doc_url: https://fmpy.readthedocs.io/
  dev_url: https://github.com/CATIA-Systems/FMPy

extra:
  recipe-maintainers:
    - t-sommer
    - wulmer
