{% set version = "0.2.20" %}

package:
  name: fmpy
  version: {{ version }}

source:
  url: https://github.com/CATIA-Systems/FMPy/archive/v{{ version }}.tar.gz
  sha256: e80249e62400e286d1d1d828ccb45f255e77dfd10e6e4c0df0084dfba8d5d63d
  # macOS: shasum -a 256 <file>

build:
  number: 0
  skip: true  # [win and vc<14]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - fmpy = fmpy.command_line:main

requirements:
  build:
    - python
    - pip
    - lxml
    - numpy
    - pathlib
    - pyqt
    - pywin32  # [win]
  run:
    - python
    - dask
    - lxml
    - matplotlib
    - numpy
    - pathlib
    - pyqt
    - pyqtgraph
    - pywin32  # [win]
    - requests

test:
  imports:
    - fmpy
    - fmpy.cross_check
    - fmpy.examples
    - fmpy.gui
    - fmpy.ssp
    - fmpy.ssp.examples
    - fmpy.sundials

about:
  home: https://github.com/CATIA-Systems/FMPy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Simulate Functional Mockup Units (FMUs) in Python
  doc_url: https://fmpy.readthedocs.io/
  dev_url: https://github.com/CATIA-Systems/FMPy

extra:
  recipe-maintainers:
    - t-sommer
    - wulmer
