package:
  name: fmpy
  version: 0.3.20

source:
  url: https://pypi.io/packages/py3/F/FMPy/FMPy-0.3.20-py3-none-any.whl
  sha256: 3993b4fc961c754340b100be718783f55d8169ad456ee7b376f551f278cf91d5

build:
  number: 0
  entry_points:
    - fmpy = fmpy.command_line:main

outputs:

  - name: fmpy-base
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    requirements:
      host:
        - python >=3.5
        - pip
      run:
        - python >=3.5
        - attrs
        - jinja2
        - lark
        - lxml
        - msgpack-python
        - numpy
        - pywin32  # [win]
    test:
      imports:
        - fmpy
        - fmpy.cross_check
        - fmpy.examples
        - fmpy.fmucontainer
        - fmpy.modelica
        - fmpy.ssp
        # sundials binaries require glibc>=2.29 and cannot be run on the cos7 build image
        - fmpy.sundials  # [not linux]

  - name: fmpy
    build:
      noarch: python
    requirements:
      run:
        - dash-bootstrap-components >=1.0.0
        - dask
        - matplotlib-base
        - notebook
        - plotly
        - pyqt
        - pyqtgraph
        - pyqtwebengine
        - python-kaleido
        - requests
        - scipy
        - {{ pin_subpackage('fmpy-base', max_pin="x.x.x") }}
    test:
      imports:
        - fmpy.gui
        - fmpy.webapp

about:
  home: https://github.com/CATIA-Systems/FMPy
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Simulate Functional Mockup Units (FMUs) in Python
  doc_url: https://fmpy.readthedocs.io/
  dev_url: https://github.com/CATIA-Systems/FMPy

extra:
  recipe-maintainers:
    - t-sommer
    - wulmer
