package:
  name: fmpy
  version: 0.3.11

source:
  url: https://files.pythonhosted.org/packages/39/0d/ece7dac0ebcd7a5094e81b93c7075f108941889609c3607c1cea2b6a4a0f/FMPy-0.3.11-py3-none-any.whl
  sha256: 64935a7f2f13240a71c125bf09efe49156cf5cf88cd24fc2f19f8f748af02941
  # macOS: shasum -a 256 <file>
  # Windows: certutil -hashfile <file> SHA256

build:
  number: 0
  skip: true  # [win and vc<14]
  entry_points:
    - fmpy = fmpy.command_line:main

outputs:

  - name: fmpy-base
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - attrs
        - jinja2
        - lark-parser
        - lxml
        - msgpack-python
        - numpy
        - pathlib
        - pywin32  # [win]
        - pytz
        - requests
    test:
      imports:
        - fmpy
        - fmpy.cross_check
        - fmpy.examples
        - fmpy.fmucontainer
        - fmpy.modelica
        - fmpy.ssp
        - fmpy.sundials

  - name: fmpy
    build:
      noarch: python
    requirements:
      run:
        - dash-bootstrap-components
        - dask
        - matplotlib-base
        - nbformat
        - pyqt
        - pyqtgraph
        - {{ pin_subpackage('fmpy-base', max_pin="x.x.x") }}
    test:
      imports:
        - fmpy.gui
        - fmpy.webapp

about:
  home: https://github.com/CATIA-Systems/FMPy
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Simulate Functional Mockup Units (FMUs) in Python
  doc_url: https://fmpy.readthedocs.io/
  dev_url: https://github.com/CATIA-Systems/FMPy

extra:
  recipe-maintainers:
    - t-sommer
    - wulmer
