{% set name = "fmpy" %}
{% set version = "0.2.12" %}
{% set sha = "f0a616473e4f245a2259e65e1c236f66b6899976158fef6624d3d7a71dc3c89b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CATIA-Systems/FMPy/archive/v{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  number: 0
  # No qt 5.9 on vc9.
  skip: True  # [win and py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - fmpy = fmpy.command_line:main

requirements:
  build:
    - lxml
    - numpy
    - pathlib
    - pip
    - pyqt
    - python
    - pywin32  # [win]
  run:
    - dask
    - lxml
    - matplotlib
    - numpy
    - pathlib
    - python
    - pyqt
    - pyqtgraph
    - pywin32  # [win]
    - requests

test:
  imports:
    - fmpy
    - fmpy.cross_check
    - fmpy.examples
    - fmpy.gui
    - fmpy.ssp
    - fmpy.ssp.examples
    - fmpy.sundials

about:
  home: https://github.com/CATIA-Systems/FMPy
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'Simulate Functional Mockup Units (FMUs) in Python'
  doc_url: https://fmpy.readthedocs.io/
  dev_url: https://github.com/CATIA-Systems/FMPy

extra:
  recipe-maintainers:
    - t-sommer
    - wulmer
