package:
  name: fmpy
  version: 0.3.4

source:
  url: https://files.pythonhosted.org/packages/9a/1f/c71b51adc38a4f961705fa4c2c2fc3cc1b81a46a662370310fedb2f60846/FMPy-0.3.4-py3-none-any.whl
  sha256: 17a335bd0321297ff405e42242ad3a6a41080f6ce28e51e619ade2a53eb1bd17
  # macOS: shasum -a 256 <file>
  # Windows: certutil -hashfile <file> SHA256

build:
  number: 0
  skip: true  # [win and vc<14]
  entry_points:
    - fmpy = fmpy.command_line:main

outputs:

  - name: fmpy-base
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - attrs
        - lark-parser
        - lxml
        - msgpack-python
        - numpy
        - pathlib
        - pywin32  # [win]
        - pytz
        - requests
    test:
      imports:
        - fmpy
        - fmpy.cross_check
        - fmpy.examples
        - fmpy.fmucontainer
        - fmpy.ssp
        - fmpy.sundials

  - name: fmpy
    build:
      noarch: python
    requirements:
      run:
        - dash-bootstrap-components
        - dask
        - matplotlib-base
        - nbformat
        - pyqt
        - pyqtgraph
        - {{ pin_subpackage('fmpy-base', max_pin="x.x.x") }}
    test:
      imports:
        - fmpy.gui
        - fmpy.webapp

about:
  home: https://github.com/CATIA-Systems/FMPy
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Simulate Functional Mockup Units (FMUs) in Python
  doc_url: https://fmpy.readthedocs.io/
  dev_url: https://github.com/CATIA-Systems/FMPy

extra:
  recipe-maintainers:
    - t-sommer
    - wulmer
