package:
  name: fmpy
  version: 0.3.8

source:
  url: https://files.pythonhosted.org/packages/19/12/15459fc828e7a90eb7b8e1b91b15fdca05a74a36b3d0352e3ea3ee5dce8d/FMPy-0.3.8-py3-none-any.whl
  sha256: adb5baecaa179557af138ba2c5b7df1298769e8cc841c3b319bb255860aadccd
  # macOS: shasum -a 256 <file>
  # Windows: certutil -hashfile <file> SHA256

build:
  number: 0
  skip: true  # [win and vc<14]
  entry_points:
    - fmpy = fmpy.command_line:main

outputs:

  - name: fmpy-base
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - attrs
        - lark-parser
        - lxml
        - msgpack-python
        - numpy
        - pathlib
        - pywin32  # [win]
        - pytz
        - requests
    test:
      imports:
        - fmpy
        - fmpy.cross_check
        - fmpy.examples
        - fmpy.fmucontainer
        - fmpy.ssp
        - fmpy.sundials

  - name: fmpy
    build:
      noarch: python
    requirements:
      run:
        - dash-bootstrap-components
        - dask
        - matplotlib-base
        - nbformat
        - pyqt
        - pyqtgraph
        - {{ pin_subpackage('fmpy-base', max_pin="x.x.x") }}
    test:
      imports:
        - fmpy.gui
        - fmpy.webapp

about:
  home: https://github.com/CATIA-Systems/FMPy
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Simulate Functional Mockup Units (FMUs) in Python
  doc_url: https://fmpy.readthedocs.io/
  dev_url: https://github.com/CATIA-Systems/FMPy

extra:
  recipe-maintainers:
    - t-sommer
    - wulmer
