{% set version = "0.2.25" %}

package:
  name: fmpy
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/d5/00/a124dd64f60457686d4dbb0f944260a9f443e726f3ac3772f8b67230ba36/FMPy-0.2.25-py2.py3-none-any.whl
  sha256: 64ac2bdcaff1ffb7addf5e93181548e3eaafe8d704647659571efa6cffeaf804
  # macOS: shasum -a 256 <file>
  # Windows: certutil -hashfile <file> SHA256

build:
  number: 0
  skip: true  # [win and vc<14]
  entry_points:
    - fmpy = fmpy.command_line:main

outputs:

  - name: fmpy-base
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - lark-parser
        - lxml
        - numpy
        - pathlib
        - pywin32  # [win]
        - requests
    test:
      imports:
        - fmpy
        - fmpy.cross_check
        - fmpy.examples
        - fmpy.ssp
        - fmpy.ssp.examples
        - fmpy.sundials

  - name: fmpy
    build:
      noarch: python
    requirements:
      run:
        - dash-bootstrap-components
        - dask
        - matplotlib-base
        - pyqt
        - pyqtgraph
        - {{ pin_subpackage('fmpy-base', max_pin="x.x.x") }}
    test:
      imports:
        - fmpy.gui
        - fmpy.webapp

about:
  home: https://github.com/CATIA-Systems/FMPy
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Simulate Functional Mockup Units (FMUs) in Python
  doc_url: https://fmpy.readthedocs.io/
  dev_url: https://github.com/CATIA-Systems/FMPy

extra:
  recipe-maintainers:
    - t-sommer
    - wulmer
