{% set version = "0.2.23" %}

package:
  name: fmpy
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/94/d6/f135772acf6691808363daedac6d01198edce1e9f15abdb4d74b1117650c/FMPy-0.2.23-py2.py3-none-any.whl
  sha256: 45892f7a489fdfd2b8c4e1716a97396cc43e7b42505a1c0ca4dfb1a85016f706
  # macOS: shasum -a 256 <file>

build:
  number: 1
  skip: true  # [win and vc<14]
  script: 'for %%f in (*.whl) do pip install --no-deps -vv "%%f"'  # [win]
  script: {{ PYTHON }} -m pip install --no-deps -vv *.whl  # [not win]

  entry_points:
    - fmpy = fmpy.command_line:main

requirements:
  build:
    - python
    - pip
    - lxml
    - numpy
    - pathlib
    - pyqt
    - pywin32  # [win]
  run:
    - python
    - dask
    - lark-parser
    - lxml
    - matplotlib-base
    - numpy
    - pathlib
    - pyqt
    - pyqtgraph
    - pywin32  # [win]
    - requests

test:
  imports:
    - fmpy
    - fmpy.cross_check
    - fmpy.examples
    - fmpy.gui
    - fmpy.ssp
    - fmpy.ssp.examples
    - fmpy.sundials

about:
  home: https://github.com/CATIA-Systems/FMPy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Simulate Functional Mockup Units (FMUs) in Python
  doc_url: https://fmpy.readthedocs.io/
  dev_url: https://github.com/CATIA-Systems/FMPy

extra:
  recipe-maintainers:
    - t-sommer
    - wulmer
