appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: hc8lsMgPhpu5FalIWzXxVRp7qc+oEewilOLhQNvr6wqB0EhrBiYFl4Oc7i4yEMEZQB2i2e1ZSdYwW7JuIssPj96zLJFS9+fHAwkvDK1isbYGqQpfsPFTVOSbusCdq8JRu6rRqhVLVbIwjv8t0USmTkxFfY5G2bt4Sn6zq90Su2PwVECmpDGbmxxtK3OlCPcIROTbnOuPq0HWdxnhFdhJgjq+j6vjP4WkFTI/RdUTQ01ArXGCoXWkvpaZXc32P0+5ICybvSX0HsV9Mx+a4KZegtIx6iGZTnAN64kdHjSd5tSDDXBohnnjEJM6WYljMSX3pqYRCtvRHysHOhcQSNp2FdWkFFwOejNQOkPhlhvqbU8JM0DUPgVFt+AeAHHlMm+i+ei0TChAXIah+rU6jhAg9o3lYtJi1okG6W4Gx2ZKyHXXzJnWTIenjK3MOPzjR+His8kaJMtqOCpEVChjFlh1IolJnjVz5vKaFwIwTyejR43GL2ZtxXq8vTh45riZPTIu3NtusLBRAUo5yrsMNaWIW7QfKMukAdlS/4MOaTDO9ns4N+5GSNbcEwCy6lvvoWowsO8BIKfeBNmRem4Y/A16VVbDg+6udZvz5110UUUNsPcGMESvNa47LyvgodhiPABf38lyWiyoJf95glZp4m1mBY7WNXcG/QAwkTQxWlvoJIw=}
provider:
  win: azure
